apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  template:
    spec:
      volumes:
      - name: data-input
        gcePersistentDisk:
          pdName: glow-data-disk-200
          fsType: ext4
      - name: data-output
        emptyDir: {}
      initContainers:
      - name: init
        image: google/cloud-sdk:275.0.0-alpine
        command:
        - /bin/sh
        - -c
        - gsutil -m rsync -dr gs://glow-sportradar/ /data/input
        volumeMounts:
        - name: data-input
          mountPath: /data/input
      containers:
      - name: init
        image: google/cloud-sdk:275.0.0-alpine
        command:
        - /bin/sh
        - -c
        - gsutil -m rsync -dr gs://glow-sportradar/ /data/input
        lifecycle:
          postStart:
            exec:
              command: []
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Stop from the..."]
        volumeMounts:
        - name: data-input
          mountPath: /data/input
      restartPolicy: Never
  backoffLimit: 0
